# Generated by Django 4.2.3 on 2023-12-07 17:46

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_aplication_status_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplication',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложение'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='aplication',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aplication',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='aplication',
            name='second_photo',
            field=models.ImageField(null=True, upload_to=project.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), project.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
